name: internet_popup
description: A package for popUp message when Internet connection is off. Write
  one line to initialize a popUp when internet connection is turned off or
  connected but no internet.

version: 1.0.8+5
homepage: https://github.com/mehedidew/internet_popup

environment:
  sdk: ">=2.17.3 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  connectivity_plus: ^3.0.3
  flutter:
    sdk: flutter
  internet_connection_checker: ^1.0.0+1

dev_dependencies:
  flutter_lints: ^2.0.1
  test: ^1.21.4
